### ISSUE TITLE
gifs and images used in the GUI haven't been uploaded

### ISSUE THREAD

**Issue by qarchli** [sburl/ReorderWhat#2]
`Traceback (most recent call last):
  File "desktopGUI.py", line 959, in <module>
    run(600, 600)
  File "desktopGUI.py", line 953, in run
    timerFiredWrapper(canvas, data)
  File "desktopGUI.py", line 933, in timerFiredWrapper
    redrawAllWrapper(canvas, data)
  File "desktopGUI.py", line 920, in redrawAllWrapper
    redrawAll(canvas, data)
  File "desktopGUI.py", line 908, in redrawAll
    drawBackground(canvas, data)
  File "desktopGUI.py", line 883, in drawBackground
    drawBasis(canvas, data)
  File "desktopGUI.py", line 720, in drawBasis
    makeBasisImage(canvas, data)
  File "desktopGUI.py", line 674, in makeBasisImage
    data.photo = PhotoImage(file = "forklift.gif")
  File "/anaconda3/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/anaconda3/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "forklift.gif": no such file or directory
`

**Comment by sburl** [comment]
This project is unmaintained and not under active development — closing open reports. Thanks for trying it out.
